# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parent
pod 'MJRefresh'
pod 'Alamofire'
pod 'JHB_HUDView'
pod 'Kingfisher'
pod 'SnapKit'
pod 'BFKit-Swift'

end
